# housing :: docker-compose

networks:
  locally:

services:
  wwwroot:
    build:
      args:
        - NGINX_VERSION=alpine
        - NODE_VERSION=alpine
      context: ./wwwroot
      dockerfile: ../.docker/dockerfile
      labels:
        - "xyz.alpine.maintainer=fred belotte"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    image: housing
    labels:
      - "xyz.alpine.maintainer=fred belotte"
    networks:
      - locally
    ports:
      - 9000:80
      - 9001:443
    restart: on-failure

version: '3.7'
