# housing :: docker-compose

networks:
  locally:

services:
  housing:
    build:
      args:
        - NGINX_VERSION=alpine
        - NODE_VERSION=alpine
      context: ./housing
      dockerfile: ../.docker/dockerfile
    dns:
      - 1.1.1.1
      - 1.0.0.1
    image: housing
    networks:
      - locally
    ports:
      - 9000:80
      - 9001:443
    restart: on-failure

version: '3.7'
